module.exports = {
	ptBR : {
		invId : "Id inválido",
		invCouponId : "Id do cupom inválido",
		invUserId : "Id do usuário inválido",
		invUserName : "Nome do usuário inválido",
		invOrderId : "Id do pedido inválido",
		invProductId : "Id do produto inválido",
		invProductName : "Nome do produto inválido",
		invProductType : "Tipo do produto inválido",
		invProductPrice : "Preço(s) do produto inválido(s)",
		invProductSize : "Tamanho(s) do produto inválido(s)",
		invProductPriceSize : "Preço e tamanho incompatíveis",
		invProductIngredients : "Ingrediente(s) do produto inválido(s)",
		invAdditionId : "Id da adição inválido",
		invAdditionName : "Nome da adição inválido",
		invAdditionType : "Tipo(s) da adição inválido(s)",
		invAdditionPrice : "Preço da adição inválido",
		invEmail : "Email inválido",
		invPhone : "Telefone inválido",
		invAddress : "Endereço inválido",
		invPassword : "Senha inválida",
		invNewPassword : "Nova senha inválida",
		invPasswordConfirmation : "Confirmação de senha inválida",
		invToken : "Token inválido",
		succAdditionCreate : "Adição criada com sucesso",
		succAdditionUpdate : "Adição alterada com sucesso",
		succAdditionUpdateThumb : "Imagem da adição alterada com sucesso",
		succAdditionUpdateButThumb : "Imagem da adição alterada com sucesso, porém a imagem antiga não foi encontrada",
		succAdditionDelete : "Adição removida com sucesso",
		succAdditionDeleteButThumb : "Adição removida com sucesso, porém a imagem antiga não foi encontrada",
		succProductCreate : "Produto criado com sucesso",
		succProductUpdate : "Informações do produto alteradas com sucesso",
		succProductUpdateThumb : "Imagem do produto alterada com sucesso",
		succProductUpdateButThumb : "Imagem do produto alterada com sucesso, porém a imagem antiga não foi encontrada",
		succProductDelete : "Produto removido com sucesso",
		succProductDeleteButThumb : "Produto removido com sucesso, porém a imagem antiga não foi encontrada",
		succOrderCreate : "Pedido criado com sucesso",
		succOrderUpdate : "Informações do pedido alteradas com sucesso",
		succOrderDelete : "Pedido removido com sucesso",
		succUserCreate : "Usuário criado com sucesso",
		succUserUpdate : "Informações do usuário alteradas com sucesso",
		succUserUpdateThumb : "Foto de perfil do usuário alterada com sucesso",
		succUserUpdateButThumb : "Foto de perfil do usuário alterada com sucesso, porém a foto de perfil antiga não foi encontrada",
		succUserDelete : "Usuário removido com sucesso",
		succUserDeleteButThumb : "Usuário removido com sucesso, porém a foto de perfil antiga não foi encontrada",
		failAdditionCreate : "Não foi possível criar uma nova adição",
		failAdditionUpdate : "Não foi possível alterar as informações da adição",
		failAdditionDelete : "Não foi possível remover a adição",
		failProductCreate : "Não foi possível criar um novo produto",
		failProductUpdate : "Não foi possível alterar as informações do produto",
		failProductDelete : "Não foi possível remover o produto",
		failOrderCreate : "Não foi possível criar um pedido",
		failOrderUpdate : "Não foi possível alterar as informações do pedido",
		failOrderDelete : "Não foi possível remover o pedido",
		failUserCreate : "Não foi possível criar um usuário",
		failUserUpdate : "Não foi possível alterar as informações do usuário",
		failUserDelete : "Não foi possível remover o usuário",
		unauthOperation : "Operação não autorizada",
		existentEmail : "Já há uma conta com este email",
		wrongPassword : "Senha incorreta",
		wrongPasswordConfirmation : "Senha de confirmação incorreta",
		wrongOldPassword : "Senha antiga incorreta",
		nFUser : "Usuário não encontrado",
		nFUsers : "Nenhum usuário encontrado",
		nFOrder : "Pedido não encontrado",
		nFOrders : "Nenhum pedido encontrado",
		nFAddition : "Adição não encontrada",
		nFAdditions : "Nenhuma adição encontrada",
		nFProduct : "Produto não encontrado",
		nFProducts : "Nenhum produto encontrado",
		nFCoupon : "Cupom não encontrado",
		nFCoupons : "Nenhum cupom encontrado",
		nFCompanyInfo : "Informações da empresa não encontradas",
		noToken : "Nenhum token fornecido",
		closedCompany : "Empresa está fechada"
	},
	enUS : {
		invId : "Invalid Id",
		invCouponId : "Invalid coupon id",
		invUserId : "Invalid user Id",
		invUserName : "Invalid user name",
		invOrderId : "Invalid order Id",
		invProductId : "Invalid product Id",
		invProductName : "Invalid product name",
		invProductType : "Invalid product type",
		invProductPrice : "Invalid product price(s)",
		invProductSize : "Invalid product size(s)",
		invProductPriceSize : "Incompatible price(s) and size(s)",
		invProductIngredients : "Invalid product ingredient(s)",
		invAdditionId : "Invalid addition Id",
		invAdditionName : "Invalid addition name",
		invAdditionType : "Invalid addition type(s)",
		invAdditionPrice : "Invalid addition price",
		invEmail : "Invalid email",
		invPhone : "Invalid phone",
		invAddress : "Invalid address",
		invPassword : "Invalid password",
		invNewPassword : "Invalid new password",
		invPasswordConfirmation : "Invalid password confirmation",
		invToken : "Invalid token",
		succAdditionCreate : "Addition created successfully",
		succAdditionUpdate : "Addition info updated successfully",
		succAdditionUpdateThumb : "Addition image updated successfully",
		succAdditionUpdateButThumb : "Addition image updated successfully, but its old image was not found",
		succAdditionDelete : "Addition deleted successfully",
		succAdditionDeleteButThumb : "Addition deleted successfully, but its old image was not found",
		succProductCreate : "Product created successfully",
		succProductUpdate : "Product info updated successfully",
		succProductUpdateThumb : "Product image updated successfully",
		succProductUpdateButThumb : "Product image updated successfully, but its old image was not found",
		succProductDelete : "Product deleted successfully",
		succProductDeleteButThumb : "Product deleted successfully, but its old image was not found",
		succOrderCreate : "Order created successfully",
		succOrderUpdate : "Product info updated successfully",
		succOrderDelete : "Order deleted successfully",
		succUserCreate : "User created successfully",
		succUserUpdate : "User info updated successfully",
		succUserUpdateThumb : "User profile pic updated successfully",
		succUserUpdateButThumb : "User profile pic updated successfully, but its old profile pic was not found",
		succUserDelete : "User deleted successfully",
		succUserDeleteButThumb : "User deleted successfully, but its old profile pic was not found",
		failAdditionCreate : "A new addition could not be created",
		failAdditionUpdate : "Addition info could not be changed",
		failAdditionDelete : "Addition could not be deleted",
		failProductCreate : "A new product could not be created",
		failProductUpdate : "Product info could not be changed",
		failProductDelete : "Product could not be deleted",
		failOrderCreate : "A new order could not be created",
		failOrderUpdate : "Order info could not be changed",
		failOrderDelete : "Order could not be deleted",
		failUserCreate : "A new user could not be created",
		failUserUpdate : "User info could not be changed",
		failUserDelete : "User could not be deleted",
		unauthOperation : "Unauthorized operation",
		existentEmail : "There is already an account using this email",
		wrongPassword : "Wrong password",
		wrongPasswordConfirmation : "Wrong confirmation password",
		wrongOldPassword : "Wrong old password",
		nFUser : "User not found",
		nFUsers : "Users not found",
		nFOrder : "Order not found",
		nFOrders : "Orders not found",
		nFAddition : "Addition not found",
		nFAdditions : "Additions not found",
		nFProduct : "Product not found",
		nFProducts : "Products not found",
		nFCoupon : "Coupon not found",
		nFCoupons : "Coupons not found",
		nFCompanyInfo : "Company info not found",
		noToken : "No token provided",
		closedCompany : "Company is closed"
	}
};