//	Chosen language
const lang = "ptBR";

module.exports = {
	ptBR : {
		invId : "Id inválido",
		invUserName : "Nome do usuário inválido",
		invProductName : "Nome do produto inválido",
		invProductType : "Tipo do produto inválido",
		invProductPrice : "Preço(s) do produto inválido(s)",
		invProductSize : "Tamanho(s) do produto inválido(s)",
		invProductPriceSize : "Preço e tamanho incompatíveis",
		invProductIngredients : "Ingrediente(s) do produto inválido(s)",
		invAdditionName : "Nome da adição inválido",
		invAdditionType : "Tipo(s) da adição inválido(s)",
		invAdditionPrice : "Preço da adição inválido",
		invCouponName : "Nome do cupom inválido",
		invCouponDiscount : "Desconto do cupom inválido",
		invCouponType : "Tipo do cupom inválido",
		invCouponTypeMethod : "Tipo e método incompatíveis",
		invCouponTypeScope : "Tipo e escopo incompatíveis",
		invCouponTypeMinValue : "Tipo e valor mínimo incompatíveis",
		invCouponUserScope : "Usuário e escopo incompatíveis",
		invCouponAvailable : "Disponibilidade do cupom inválida",
		invCouponQty : "Quantidade do cupom inválido",
		invCouponScope : "Escopo (público ou privado) do cupom inválido",
		invCouponMethod : "Método do cupom inválido",
		invEmail : "Email inválido",
		invPhone : "Telefone inválido",
		invAddress : "Endereço inválido",
		invPassword : "Senha inválida",
		invNewPassword : "Nova senha inválida",
		invPasswordConfirmation : "Confirmação de senha inválida",
		invToken : "Token inválido",
		succAdditionCreate : "Adição criada com sucesso",
		succAdditionUpdate : "Informações da adição alteradas com sucesso",
		succAdditionUpdateThumb : "Imagem da adição alterada com sucesso",
		succAdditionUpdateButThumb : "Imagem da adição alterada com sucesso, porém a imagem antiga não foi encontrada",
		succAdditionDelete : "Adição removida com sucesso",
		succAdditionDeleteButThumb : "Adição removida com sucesso, porém a imagem antiga não foi encontrada",
		succProductCreate : "Produto criado com sucesso",
		succProductUpdate : "Informações do produto alteradas com sucesso",
		succProductUpdateThumb : "Imagem do produto alterada com sucesso",
		succProductUpdateButThumb : "Imagem do produto alterada com sucesso, porém a imagem antiga não foi encontrada",
		succProductDelete : "Produto removido com sucesso",
		succProductDeleteButThumb : "Produto removido com sucesso, porém a imagem antiga não foi encontrada",
		succOrderCreate : "Pedido criado com sucesso",
		succOrderUpdate : "Informações do pedido alteradas com sucesso",
		succOrderDelete : "Pedido removido com sucesso",
		succUserCreate : "Usuário criado com sucesso",
		succUserUpdate : "Informações do usuário alteradas com sucesso",
		succUserUpdateThumb : "Foto de perfil do usuário alterada com sucesso",
		succUserUpdateButThumb : "Foto de perfil do usuário alterada com sucesso, porém a foto de perfil antiga não foi encontrada",
		succUserDelete : "Usuário removido com sucesso",
		succUserDeleteButThumb : "Usuário removido com sucesso, porém a foto de perfil antiga não foi encontrada",
		succCouponCreate : "Cupom criado com sucesso",
		succCouponUpdate : "Informações do cupom alteradas com sucesso",
		succCouponDelete : "Cupom removido com sucesso",
		failAdditionCreate : "Não foi possível criar uma nova adição",
		failAdditionUpdate : "Não foi possível alterar as informações da adição",
		failAdditionDelete : "Não foi possível remover a adição",
		failProductCreate : "Não foi possível criar um novo produto",
		failProductUpdate : "Não foi possível alterar as informações do produto",
		failProductDelete : "Não foi possível remover o produto",
		failOrderCreate : "Não foi possível criar um pedido",
		failOrderUpdate : "Não foi possível alterar as informações do pedido",
		failOrderDelete : "Não foi possível remover o pedido",
		failUserCreate : "Não foi possível criar um usuário",
		failUserUpdate : "Não foi possível alterar as informações do usuário",
		failUserDelete : "Não foi possível remover o usuário",
		failCouponCreate : "Não foi possível criar um novo cupom",
		failCouponUpdate : "Não foi possível alterar as informações do cupom",
		failCouponDelete : "Não foi possível remover o cupom",
		unauthOperation : "Operação não autorizada",
		unavailableCoupon : "Cupom indisponível para uso",
		existentEmail : "Já há uma conta com este email",
		existentCoupon : "Já há um cupom com este nome",
		wrongPassword : "Senha incorreta",
		wrongPasswordConfirmation : "Senha de confirmação incorreta",
		wrongOldPassword : "Senha antiga incorreta",
		nFUser : "Usuário não encontrado",
		nFUsers : "Nenhum usuário encontrado",
		nFOrder : "Pedido não encontrado",
		nFOrders : "Nenhum pedido encontrado",
		nFAddition : "Adição não encontrada",
		nFAdditions : "Nenhuma adição encontrada",
		nFProduct : "Produto não encontrado",
		nFProducts : "Nenhum produto encontrado",
		nFCoupon : "Cupom não encontrado",
		nFCoupons : "Nenhum cupom encontrado",
		nFCompanyInfo : "Informações da empresa não encontradas",
		noToken : "Nenhum token fornecido",
		closedCompany : "Empresa está fechada"
	},
	enUS : {
		invId : "Invalid Id",
		invUserName : "Invalid user name",
		invProductName : "Invalid product name",
		invProductType : "Invalid product type",
		invProductPrice : "Invalid product price(s)",
		invProductSize : "Invalid product size(s)",
		invProductPriceSize : "Incompatible price(s) and size(s)",
		invProductIngredients : "Invalid product ingredient(s)",
		invAdditionName : "Invalid addition name",
		invAdditionType : "Invalid addition type(s)",
		invAdditionPrice : "Invalid addition price",
		invCouponName : "Invalid coupon name",
		invCouponDiscount : "Invalid coupon discount",
		invCouponType : "Invalid coupon type",
		invCouponTypeMethod : "Incompatible type and method",
		invCouponTypeScope : "Incompatible type and scope",
		invCouponTypeMinValue : "Incompatible type and minimum value",
		invCouponUserScope : "Incompatible user and scope",
		invCouponAvailable : "Invalid coupon available",
		invCouponQty : "Invalid coupon quantity",
		invCouponScope : "Invalid coupon scope (public or private)",
		invCouponMethod : "Invalid coupon method",
		invEmail : "Invalid email",
		invPhone : "Invalid phone",
		invAddress : "Invalid address",
		invPassword : "Invalid password",
		invNewPassword : "Invalid new password",
		invPasswordConfirmation : "Invalid password confirmation",
		invToken : "Invalid token",
		succAdditionCreate : "Addition created successfully",
		succAdditionUpdate : "Addition info updated successfully",
		succAdditionUpdateThumb : "Addition image updated successfully",
		succAdditionUpdateButThumb : "Addition image updated successfully, but its old image was not found",
		succAdditionDelete : "Addition deleted successfully",
		succAdditionDeleteButThumb : "Addition deleted successfully, but its old image was not found",
		succProductCreate : "Product created successfully",
		succProductUpdate : "Product info updated successfully",
		succProductUpdateThumb : "Product image updated successfully",
		succProductUpdateButThumb : "Product image updated successfully, but its old image was not found",
		succProductDelete : "Product deleted successfully",
		succProductDeleteButThumb : "Product deleted successfully, but its old image was not found",
		succOrderCreate : "Order created successfully",
		succOrderUpdate : "Product info updated successfully",
		succOrderDelete : "Order deleted successfully",
		succUserCreate : "User created successfully",
		succUserUpdate : "User info updated successfully",
		succUserUpdateThumb : "User profile pic updated successfully",
		succUserUpdateButThumb : "User profile pic updated successfully, but its old profile pic was not found",
		succUserDelete : "User deleted successfully",
		succUserDeleteButThumb : "User deleted successfully, but its old profile pic was not found",
		succCouponCreate : "Coupon created successfully",
		succCouponUpdate : "Coupon info updated successfully",
		succCouponDelete : "Coupon deleted successfully",
		failAdditionCreate : "A new addition could not be created",
		failAdditionUpdate : "Addition info could not be updated",
		failAdditionDelete : "Addition could not be deleted",
		failProductCreate : "A new product could not be created",
		failProductUpdate : "Product info could not be updated",
		failProductDelete : "Product could not be deleted",
		failOrderCreate : "A new order could not be created",
		failOrderUpdate : "Order info could not be updated",
		failOrderDelete : "Order could not be deleted",
		failUserCreate : "A new user could not be created",
		failUserUpdate : "User info could not be updated",
		failUserDelete : "User could not be deleted",
		failCouponCreate : "A new coupon could not be created",
		failCouponUpdate : "Coupon info could not be updated",
		failCouponDelete : "Coupon could not be deleted",
		unauthOperation : "Unauthorized operation",
		unavailableCoupon : "Coupon unavailable for use",
		existentEmail : "There is already an account using this email",
		existentCoupon : "There is already a coupon using this name",
		wrongPassword : "Wrong password",
		wrongPasswordConfirmation : "Wrong confirmation password",
		wrongOldPassword : "Wrong old password",
		nFUser : "User not found",
		nFUsers : "Users not found",
		nFOrder : "Order not found",
		nFOrders : "Orders not found",
		nFAddition : "Addition not found",
		nFAdditions : "Additions not found",
		nFProduct : "Product not found",
		nFProducts : "Products not found",
		nFCoupon : "Coupon not found",
		nFCoupons : "Coupons not found",
		nFCompanyInfo : "Company info not found",
		noToken : "No token provided",
		closedCompany : "Company is closed"
	}
}[lang];